<?php /** @var Apedik\AiBlog\Block\Adminhtml\Post\Edit\Tab\Post $block */ ?>
<script type='text/javascript'>
    function sendAIRequest(requestType, postName, useSameShortMetaDescription) {
        jQuery('#post_post_content').trigger('processStart');

        let requestData = {
            'form_key': "<?= $block->getFormKey() ?>",
            'post_name': postName,
            'request_type': requestType,
        };

        jQuery.ajax({
            url: "<?= $block->getBackendUrl()->getUrl('airequest/index/index') ?>",
            type: 'POST',
            data: requestData,
            dataType: 'json',
            beforeSend: function (xhr) {
                // Any pre-request actions
            },
            success: function (response) {
                jQuery('#post_post_content').trigger('processStop')
                let messageContent = response.choices[0].message.content;

                if (requestType === 'description' && useSameShortMetaDescription === true) {
                    jQuery('#post_meta_description, #post_short_description').val(messageContent);
                } else if (requestType === 'post') {
                    jQuery('#post_post_content').trigger('processStop').val(messageContent);
                } else {
                    jQuery('#post_meta_description').val(messageContent);
                }
            }
        });
    }

    function AIGenerateDescription() {
        let postName = jQuery('#post_name').val();
        sendAIRequest('description', postName, <?= $block->getConfig()->useSameShortMetaDescription() === true ?>);
    }

    function AIGeneratePost() {
        jQuery('#togglepost_post_content').click();
        let postName = jQuery('#post_name').val();
        sendAIRequest('post', postName, false);
    }
</script>

